### ISSUE TITLE
Android App Doesn't Show Dots on Map

### ISSUE THREAD

**Issue by rbrtmnz** [WorkingFamilies/votivate#44] opened 2019-02-04 22:52 UTC
**Environment:**
 - Android
 - Mobile Device

**Detailed Description**
No dots on map using Android phone. I was able to assign the turf to myself on an iPhone and there were no issues. Campaign is NY Volunteer Texting and the Targeting is Volunteer Recruit Uni 1.

**Does It Have a Workaround?**
List View

**Screenshots**
I didn't get this from Dylan but just imagine a map of Crown Heights with no dots on it.

**Comment by codygordon** [comment] 2019-02-04 23:12
The workaround is to select the menu, go back to the turfs list, then re-select the turf.

**Comment by rbrtmnz** [comment] 2019-02-04 23:15
That was the first thing I tried. It was also the only thing I tried.

**Comment by joemcl** [comment] 2019-02-08 17:51
I'm using Votivate Clipboard latest version on a Pixel 3 XL running Android 9. When I click in the correct geographic area for 87 16th St in BK, in a turf that was created and assigned to me, this comes up - meaning the map point was found, but the icon just does not show on the map - 
![screenshot_20190204-132108 1](https://user-images.githubusercontent.com/3912434/52496034-29994280-2b87-11e9-833f-8317297e8615.png)

**Comment by joemcl** [comment] 2019-02-08 17:58
and @codygordon the workaround you recommend above did not make any difference - I had tried that before seeing the comment above.

**Comment by codygordon** [comment] 2019-02-12 17:21
Pretty sure this is fixed, after updating the app I can't recreate it on my Android device. 

If it persists, it could be device-specific which would make it hard to pinpoint.

**Comment by joemcl** [comment] 2019-02-25 18:47
thx @codygordon I'll update the app on my phone and check it out

**Comment by joemcl** [comment] 2019-02-25 18:52
@codygordon uninstalled, reinstalled Android version and get this error message: 
![screenshot_20190225-104932](https://user-images.githubusercontent.com/3912434/53360807-65ecd280-38eb-11e9-866b-edb970ee14d1.png)

**Comment by codygordon** [comment] 2019-02-25 19:42
Should load correctly after just hitting that reload arrow when the app opens (if the error is still showing).

**Comment by joemcl** [comment] 2019-02-25 19:49
Yeah it doesn't though - I uninstalled and reinstalled again too. Maybe error is caused by me not having a current assigned turf, so I'll create one for myself. Also, with that error showing, don't see any way to log out or log back in to the app to refresh that way, if doable.

**Comment by joemcl** [comment] 2019-02-25 19:51
OK aha so just opened up the app again, and could log back in, cool. Now see "You haven't been assigned any turfs for today" etc so I'll create one and assign it to myself...

**Comment by joemcl** [comment] 2019-02-25 19:56
aargh but as a "Supervolunteer" role, I can't cut a turf, so guess someone has to create one for me here - 
![226db97a-bf15-40cc-919c-28d9b5eec587](https://user-images.githubusercontent.com/3912434/53364752-56be5280-38f4-11e9-9500-de4ef93713f1.jpg)

**Comment by joemcl** [comment] 2019-02-26 21:00
@deasterdaywfp ^^^

**Comment by deasterdaywfp** [comment] 2019-02-26 21:01
@joemcl I will cut one to test sure!

**Comment by joemcl** [comment] 2019-02-26 21:19
Thx

**Comment by deasterdaywfp** [comment] 2019-02-26 21:30
No problem. I just retested and yeah, this is still an issue. At least on
android devices (I'm using Samsung S9) and a universe of about 3K in NY
Volunteer Texting targeting

*Dylan Easterday*
*National Volunteer Manager, Digital - Working Families Party*
*Working Families <http://workingfamilies.org>*
*Text *(347) 460-9451 or Schedule https://calendly.com/deasterday
Email deasterday@workingfamilies.org
Done with email? me too - join me here <http://bit.ly/WFP4theMany>

**Comment by joemcl** [comment] 2019-02-26 22:31
I now see houses/map points in the Android app -

**Comment by joemcl** [comment] 2019-02-26 22:38
On the Android app, I can now see map points....

**Comment by joemcl** [comment] 2019-02-26 22:43
@deasterdaywfp did you uninstall and reinstall, log out and log back in? Have the latest version of the app?

**Comment by deasterdaywfp** [comment] 2019-02-26 22:50
I see sorry I had not. Now that's done and all working great!

**Comment by joemcl** [comment] 2019-02-26 23:01
Cool yay

**Comment by joemcl** [comment] 2019-02-26 23:08
So @robtmnz looks like you can close this Issue

**Comment by joemcl** [comment] 2019-02-28 20:20
And thanks again @codygordon for the fix!

**Closed** 2019-03-04 17:49 UTC
Labels: Clipboard (mobile), bug
