### ISSUE TITLE
Votivate App Crashing

### ISSUE THREAD

**Issue by rbrtmnz** [WorkingFamilies/votivate#73] opened 2019-03-18 21:14 UTC
**Environment:**
Android and Apple

**Detailed Description**
It crashes whenever you click on the household and/or voter name. This occurs in both map view and list view. It is also occurring on all devices. Some canvassers are kicked to a completely white screen and then back to the home page. Others are kicked to the screen seen in the attachment.

**Does It Have a Workaround?**
Nope

**Screenshots**
![image](https://user-images.githubusercontent.com/30630157/54564108-58ce7b00-49a1-11e9-943b-1f7eb1a811d2.png)

**Comment by codygordon** [comment] 2019-03-18 21:51
I'm not able to recreate and there have been results coming in, so  I think this may have to do with some data specific to a campaign / state jamming it up... what campaign / turfs is this happening on?

**Comment by rbrtmnz** [comment] 2019-03-18 22:15
Campaign: Needleman - Field Pipeline Tax
Targeting: Portland - Mar 14
Turfs: 2, 6, 7, 8, 9, 10, 11, 14

**Comment by codygordon** [comment] 2019-03-18 22:38
Okay, got it. **If the turfs are revoked and re-assigned to the canvassers with the same sheet format, they'll work properly immediately.**

This was caused by one of the questions (`Stop Pipeline Tax Yard Sign`) not being properly sent with the sheet format (`SPT Field Script`). 

I believe the root cause was a bug where the question was first assigned at the statewide level then changed to the campaign, but a piece of data on the backend didn't register that detail so it wasn't being properly loaded. They may or may not have reported this, but a bug screen was also showing when attempting to open this sheet format in Settings. I am deploying a fix for this ASAP.

**Closed by codygordon** 2019-03-18 22:38 UTC
Labels: Clipboard (mobile), bug
